name: CD

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Render Deployment
        run: curl ${{ secrets.RENDER_DEPLOYMENT_PRD_URL }}
