name: CD

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Render Deployment
        run: curl https://api.render.com/deploy/srv-com87c0l6cac73d379lg?key=CYGszKeJAqA
