name: CD

on:
  pull_request:
    branches: ['main', 'qa']

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies and build
        run: | 
        bun install
        bun run build

      - name: Tests
        run: bun run test --passWithNoTests

      - name: Render Deployment
        uses: sws2apps/render-deployment@v1.6.0
        with:
          serviceId: ${{ secrets.RENDER_QA_SERVICE_ID }}
          apiKey: ${{ secrets.RENDER_QA_API_KEY }}
