name: CD

on:
  pull_request:
    branches: ['main']

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies and build
        run: bun install

      - name: Tests
        run: bun run test --passWithNoTests

      - name: Render Deployment
        run: curl https://api.render.com/deploy/srv-com87c0l6cac73d379lg?key=CYGszKeJAqA
